apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yfys
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-yfys@sha256:86a82fe6da76614dde934acc87ed13157d0a69bd58ed59b25817ed4e6fdbff9f
        name: my-nodejs
        resources: {}
status: {}
